import type React from 'react'

export const styles: Record<string, React.CSSProperties> = {
  toolbar: {
    position: 'fixed',
    bottom: 16,
    right: 16,
    zIndex: 9999,
    background: '#1a1614',
    border: '1px solid #3a3330',
    borderRadius: 8,
    padding: '8px 12px',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontFamily: 'monospace',
    fontSize: 13,
    color: '#e5e0d8',
    boxShadow: '0 4px 24px rgba(0,0,0,0.5)',
    flexWrap: 'wrap',
    maxWidth: 480,
  },
  fieldSection: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    borderRight: '1px solid #3a3330',
    paddingRight: 8,
  },
  fieldPath: {
    color: '#888',
    fontSize: 11,
    maxWidth: 160,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  savingBadge: {
    color: '#f59e0b',
    fontSize: 11,
  },
  btnPrimary: {
    background: '#10b981',
    color: '#fff',
    border: 'none',
    borderRadius: 4,
    padding: '3px 10px',
    fontSize: 12,
    cursor: 'pointer',
  },
  btnSecondary: {
    background: 'transparent',
    color: '#888',
    border: '1px solid #3a3330',
    borderRadius: 4,
    padding: '3px 10px',
    fontSize: 12,
    cursor: 'pointer',
  },
  btnGhost: {
    background: 'transparent',
    color: '#e5e0d8',
    border: '1px solid #3a3330',
    borderRadius: 4,
    padding: '3px 10px',
    fontSize: 12,
    cursor: 'pointer',
  },
  btnSuccess: {
    background: '#10b981',
    color: '#fff',
    border: 'none',
    borderRadius: 4,
    padding: '3px 10px',
    fontSize: 12,
    cursor: 'pointer',
  },
  btnDanger: {
    background: 'transparent',
    color: '#ef4444',
    border: '1px solid #ef4444',
    borderRadius: 4,
    padding: '2px 8px',
    fontSize: 11,
    cursor: 'pointer',
  },
  panel: {
    position: 'absolute',
    bottom: '100%',
    right: 0,
    marginBottom: 8,
    background: '#1a1614',
    border: '1px solid #3a3330',
    borderRadius: 8,
    padding: '10px 14px',
    minWidth: 280,
    maxWidth: 420,
    boxShadow: '0 4px 24px rgba(0,0,0,0.5)',
  },
  panelTitle: {
    fontSize: 11,
    color: '#888',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  changeRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '4px 0',
    borderBottom: '1px solid #2a2421',
  },
  changePath: {
    fontSize: 11,
    color: '#888',
    minWidth: 100,
    flexShrink: 0,
  },
  changeValue: {
    fontSize: 12,
    color: '#e5e0d8',
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  deployOk: {
    color: '#10b981',
    fontSize: 13,
  },
  deployPendingTitle: {
    color: '#f59e0b',
    fontSize: 13,
    marginBottom: 6,
  },
  deployPendingItem: {
    fontSize: 12,
    color: '#888',
    padding: '2px 0',
  },
}
